# Generated by Django 2.2.4 on 2021-06-27 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAppointments', '0002_cita'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['fecha']},
        ),
    ]
